export const products = [
  {
    id: 1,
    name: "Koenigsegg",
    category: "Sport",
    price: 99,
    fuel: 90,
    type: "Manual",
    usedBy: "2 People",
    description:
      "NISMO has become the embodiment of Nissans outstanding performance, inspired by the most unforgiving proving ground, the race track.",
    img: "/public/car1.png",
    rating: "5 star",
  },
  {
    id: 2,
    name: "Nissan GT - R",
    category: "Sport",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "2 People",
    description:
      "NISMO has become the embodiment of Nissans outstanding performance, inspired by the most unforgiving proving ground, the race track.",
    img: "/public/car2.png",
    rating: "5 star",
  },
  {
    id: 3,
    name: "Rolls - Royce",
    category: "Sedan",
    price: 96,
    fuel: 70,
    type: "Manual",
    usedBy: "4 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car3.png",
    rating: "5 star",
  },
  {
    id: 4,
    name: "Nissan GT - R",
    category: "Sport",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "2 People",
    description:
      "NISMO has become the embodiment of Nissans outstanding performance, inspired by the most unforgiving proving ground, the race track.",
    img: "/public/car4.png",
    rating: "5 star",
  },
  {
    id: 5,
    name: "All New Rush",
    category: "SUV",
    price: 72,
    fuel: 70,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car5.png",
    rating: "5star",
  },
  {
    id: 6,
    name: "CR - V",
    category: "SUV",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car6.png",
    rating: "5star",
  },
  {
    id: 7,
    name: "All New Terios",
    category: "SUV",
    price: 74,
    fuel: 90,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car7.png",
    rating: "5star",
  },
  {
    id: 8,
    name: "CR - V",
    category: "SUV",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car8.png",
    rating: "5star",
  },
  {
    id: 9,
    name: "MG ZX Exclusice",
    category: "Hatchback",
    price: 76,
    fuel: 70,
    type: "Manual",
    usedBy: "4 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car9.png",
    rating: "5star",
  },
  {
    id: 10,
    name: "New MG ZS",
    category: "SUV",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car10.png",
    rating: "5star",
  },
  {
    id: 11,
    name: "MG ZX Excite",
    category: "Hatchback",
    price: 74,
    fuel: 90,
    type: "Manual",
    usedBy: "4 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car11.png",
    rating: "5star",
  },
  {
    id: 12,
    name: "New MG ZS",
    category: "SUV",
    price: 80,
    fuel: 80,
    type: "Manual",
    usedBy: "6 People",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Error tempora fugit quod dolore, ab corporis! Fuga sequi commodi placeat eum saepe molestias illo, mollitia aliquam consequuntur officiis dolorum a hic.",
    img: "/public/car12.png",
    rating: "5star",
  },
];
